[package]
name = "linkify-demo"
version = "0.1.0"
authors = ["Robin Stocker <robin@nibor.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.86"
linkify = { path = ".." }
